### ISSUE TITLE
ERR_OSSL_EVP_UNSUPPORTED error when building with nodejs v18.13.0

### ISSUE THREAD

**Issue by fensoft** [jul13579/le-lan-launcher#40]
I've added set NODE_OPTIONS=--openssl-legacy-provider in build_app.cmd to make it works, see [here](https://stackoverflow.com/questions/69394632/webpack-build-failing-with-err-ossl-evp-unsupported)

**Comment by fensoft** [comment]
or use nodejs v16.9.1

**Comment by jul13579** [comment]
Hi, thanks for creating this issue and sorry for not reacting to it. I've just now gotten around to give the app a complete rewrite in typescript - switching to react in the progress and upgrading all build dependencies. Since this doesn't seem to be an issue with Node 20 (which I'm using for development and the CI is configured with), I"ll close this issue.
